# frozen_string_literal: true

require_relative 'sage/capybara/prefer_no_methods'
require_relative 'sage/capybara/avoid_explicit_visible'
require_relative 'sage/capybara/no_wait_zero'
require_relative 'sage/capybara/match_style'
require_relative 'sage/rspec/no_env_assignment'
require_relative 'sage/rspec/no_env_stubbing'
require_relative 'sage/rspec/no_rails_env_stubbing'
require_relative 'sage/rspec/no_conditionals'
require_relative 'sage/minitest/avoid_assert_nothing_raised'
require_relative 'sage/minitest/no_conditionals'
require_relative 'sage/minitest/no_env_assignment'
require_relative 'sage/minitest/no_rescue'
require_relative 'sage/rspec/avoid_not_to_raise_error'
require_relative 'sage/rspec/no_rescue'
require_relative 'sage/rails/all_with_block'
require_relative 'sage/rspec/prefer_have_http_status'
require_relative 'sage/rspec/redundant_type_and_empty'
